### PR TITLE
Updated for Django 2.0 compatibility

### PR DESCRIPTION
**Pull request by zout**
I've made the middleware compatible with Django 2.0.

Hope it makes it to the release so we don't have to maintain a pip package for a 2.0 compatible version.

### CODE REVIEW

**Comment by ferrix** [comment]
This change does not appear to be backwards compatible and all previous versions of Django (as seen on Travis) compain about the missing module called deprecation.

**Comment by ferrix** [comment]
Implemented in a backward compatible way in 1.2.0

**Comment by zout** [comment]
Will this fix be pushed to pypi?

**Comment by ferrix** [comment]
Was pushed the same day https://pypi.python.org/pypi/django-xff/1.2.0

**Pull request closed without merging**
